export const ACTION_TYPES = {
  LOAD_EVENTS_SUCCESS: 'LOAD_EVENTS_SUCCESS',
  LOAD_EVENT_DETAILS: 'LOAD_EVENT_DETAILS',
  GET_CURRENT_GEOLOCATION: 'GET_CURRENT_GEOLOCATION',
  GET_MARKERS: 'GET_MARKERS',
  SHOW_MARKER_POPOVER: 'SHOW_MARKER_POPOVER',
  ADD_COMMENT: 'ADD_COMMENT',
};
